import mongoose from 'mongoose';
import User from '../models/User.js';
import Jurisdiction from '../models/Jurisdiction.js';
import RiskZone from '../models/RiskZone.js';
import Sensor from '../models/Sensor.js';
import SensorReading from '../models/SensorReading.js';
import Alert from '../models/Alert.js';
import CitizenReport from '../models/CitizenReport.js';
import RoadSegment from '../models/RoadSegment.js';
import FieldTask from '../models/FieldTask.js';
import SOS from '../models/SOS.js';
import AlertAccuracyLog from '../models/AlertAccuracyLog.js';
import AuditLog from '../models/AuditLog.js';
import Notification from '../models/Notification.js';
import HistoricalLandslide from '../models/HistoricalLandslide.js';

export const seedDatabase = async () => {
  console.log('🌱 Clearing existing collections and seeding high-fidelity NER demo data...');

  await Promise.all([
    User.deleteMany({}),
    Jurisdiction.deleteMany({}),
    RiskZone.deleteMany({}),
    Sensor.deleteMany({}),
    SensorReading.deleteMany({}),
    Alert.deleteMany({}),
    CitizenReport.deleteMany({}),
    RoadSegment.deleteMany({}),
    FieldTask.deleteMany({}),
    SOS.deleteMany({}),
    AlertAccuracyLog.deleteMany({}),
    AuditLog.deleteMany({}),
    Notification.deleteMany({}),
    HistoricalLandslide.deleteMany({}),
  ]);

  // 1. Jurisdictions
  const jurisdictions = await Jurisdiction.insertMany([
    {
      stateId: 'MEG',
      stateName: 'Meghalaya',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      headquarters: 'Shillong',
      centerCoordinates: [91.8933, 25.5788],
      totalVillages: 6,
      activeAlertsCount: 3,
      emergencyContacts: [
        { label: 'State EOC Hotline', number: '1070' },
        { label: 'District Disaster Control Room', number: '+91-364-2222277' },
        { label: 'NDRF 1st Bn Control', number: '+91-364-2590244' },
      ],
    },
    {
      stateId: 'ASM',
      stateName: 'Assam',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      headquarters: 'Haflong',
      centerCoordinates: [93.0298, 25.1764],
      totalVillages: 6,
      activeAlertsCount: 2,
      emergencyContacts: [
        { label: 'Assam SDMA Toll-Free', number: '1079' },
        { label: 'Haflong EOC Duty Officer', number: '+91-3673-236224' },
      ],
    },
  ]);

  // 2. Users (Password: Raksha@2026) - Fixed deterministic ObjectIds across restarts
  const defaultPassword = 'Raksha@2026';

  const DEMO_IDS = {
    OFFICER_EKH: new mongoose.Types.ObjectId('650000000000000000000001'),
    OFFICER_DH: new mongoose.Types.ObjectId('650000000000000000000002'),
    FIELD_OFFICER: new mongoose.Types.ObjectId('650000000000000000000003'),
    CITIZEN: new mongoose.Types.ObjectId('650000000000000000000004'),
    SUPER_ADMIN: new mongoose.Types.ObjectId('650000000000000000000005'),
  };

  const officerUser = await User.create({
    _id: DEMO_IDS.OFFICER_EKH,
    name: 'Dr. Banlumlang Khongwir',
    phone: '9876543210',
    email: 'officer@raksha.gov.in',
    password: defaultPassword,
    role: 'OFFICER',
    status: 'ACTIVE',
    preferredLanguage: 'en',
    jurisdiction: {
      state: 'Meghalaya',
      district: 'East Khasi Hills',
      districtId: 'EKH',
    },
    officerDetails: {
      officialId: 'SDMA-MEG-014',
      department: 'SDMA',
      designation: 'Senior Disaster Management Officer & EOC Lead',
      officeContact: '+91-364-2222277',
    },
  });

  const officerDH = await User.create({
    _id: DEMO_IDS.OFFICER_DH,
    name: 'Pranab Saikia',
    phone: '9876543211',
    email: 'officer.dh@raksha.gov.in',
    password: defaultPassword,
    role: 'OFFICER',
    status: 'ACTIVE',
    preferredLanguage: 'as',
    jurisdiction: {
      state: 'Assam',
      district: 'Dima Hasao',
      districtId: 'DH',
    },
    officerDetails: {
      officialId: 'DDMA-DH-008',
      department: 'DDMA',
      designation: 'District Project Officer',
      officeContact: '+91-3673-236224',
    },
  });

  const fieldOfficerUser = await User.create({
    _id: DEMO_IDS.FIELD_OFFICER,
    name: 'Rilang Warjri',
    phone: '9876543220',
    email: 'field@raksha.gov.in',
    password: defaultPassword,
    role: 'FIELD_OFFICER',
    status: 'ACTIVE',
    preferredLanguage: 'kha',
    jurisdiction: {
      state: 'Meghalaya',
      district: 'East Khasi Hills',
      districtId: 'EKH',
      block: 'Sohra Civil Sub-Division',
    },
    fieldOfficerDetails: {
      employeeId: 'FLD-EKH-104',
      assignedBlock: 'Sohra Civil Sub-Division',
      subRole: 'ROAD_INSPECTOR',
      reportingOfficerId: officerUser._id,
    },
  });

  const citizenUser = await User.create({
    _id: DEMO_IDS.CITIZEN,
    name: 'Aiborlang Lyndem',
    phone: '9876543230',
    email: 'citizen@raksha.gov.in',
    password: defaultPassword,
    role: 'CITIZEN',
    status: 'ACTIVE',
    preferredLanguage: 'kha',
    jurisdiction: {
      state: 'Meghalaya',
      district: 'East Khasi Hills',
      districtId: 'EKH',
      village: 'Sohra',
    },
    citizenDetails: {
      village: 'Sohra',
      approxLocation: {
        type: 'Point',
        coordinates: [91.7324, 25.2986],
      },
    },
  });

  const superAdmin = await User.create({
    _id: DEMO_IDS.SUPER_ADMIN,
    name: 'MDoNER Central Admin',
    phone: '9876543299',
    email: 'admin@raksha.gov.in',
    password: defaultPassword,
    role: 'SUPER_ADMIN',
    status: 'ACTIVE',
    jurisdiction: {
      state: 'All-NER',
      district: 'All Districts',
      districtId: 'ALL',
    },
  });

  // 3. Realistic NER Villages (RiskZones)
  // Note: networkReliability is illustrative/approximate data based on known telecom infrastructure
  // (e.g., district HQs & highway corridors vs remote interior valleys & mountain gorges),
  // meant to be replaced with actual telecom coverage reports (e.g., TRAI / DoT cell tower telemetry) in production.
  const riskZones = await RiskZone.insertMany([
    // --- EAST KHASI HILLS (MEGHALAYA) ---
    {
      name: 'Sohra (Cherrapunji)',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Sohra',
      location: { type: 'Point', coordinates: [91.7324, 25.2986] },
      populationEstimate: 14200,
      networkReliability: 'STRONG', // Civil sub-division HQ / major tourism corridor
      nearestShelter: {
        name: 'Sohra Multi-Purpose Cyclone & Disaster Shelter',
        distanceKm: 1.1,
        coordinates: [91.735, 25.301],
      },
      susceptibility: {
        score: 78,
        level: 'HIGH',
        ndviCurrent: 0.44,
        ndviChange5yr: -0.16, // deforestation / mining
        distanceToMiningSiteKm: 1.8, // rat-hole coal quarrying nearby
        miningActivityType: 'Rat-hole Coal Infiltration & Limestone Quarry',
        landUseChangeFlag: true,
        slopeAngle: 41,
        elevationMeters: 1430,
        soilErodibilityIndex: 'High (Weathered Sandstone/Shale)',
        historicalLandslideDensity: 6,
      },
      currentTelemetry: {
        rainfall24h: 62,
        rainfall72h: 110,
        soilMoisture: 68,
        slopeMovementMm: 1.2,
        waterLevelMeters: 2.1,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WARNING',
        score: 64.2,
        confidence: 76,
        landslideScore: 64.2,
        flashFloodScore: 48.0,
        flashFloodWindow: 'Next 2–6 hours',
        floodExtentSqKm: 1.4,
        susceptibilityContribution: 46.5,
        triggerContribution: 53.5,
        contributingFactors: [
          { name: 'Mining Proximity & Structural Weakness', weight: 35, description: '1.8 km to rat-hole extraction shafts' },
          { name: '24h Cumulative Rainfall', weight: 30, description: '62 mm in 24h' },
          { name: '5-Year NDVI Forest Loss', weight: 20, description: '16% vegetation cover decline' },
          { name: 'Steep Escarpment Slope', weight: 15, description: '41° inclination' },
        ],
        lastEvaluated: new Date(),
      },
      assignedFieldOfficerId: fieldOfficerUser._id,
    },
    {
      name: 'Mawlynnong',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Pynursla',
      location: { type: 'Point', coordinates: [91.9056, 25.2017] },
      populationEstimate: 950,
      networkReliability: 'STRONG', // Model eco-tourism hub with active telecom micro-towers
      nearestShelter: { name: 'Mawlynnong Community Hall', distanceKm: 0.4 },
      susceptibility: {
        score: 22,
        level: 'LOW',
        ndviCurrent: 0.78,
        ndviChange5yr: 0.02,
        distanceToMiningSiteKm: 12.0,
        miningActivityType: 'None (Protected Community Reserve)',
        landUseChangeFlag: false,
        slopeAngle: 18,
        elevationMeters: 490,
        soilErodibilityIndex: 'Low (Deep Rooted Basaltic Soil)',
        historicalLandslideDensity: 0,
      },
      currentTelemetry: {
        rainfall24h: 18,
        rainfall72h: 30,
        soilMoisture: 32,
        slopeMovementMm: 0.0,
        waterLevelMeters: 0.8,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'SAFE',
        score: 14.5,
        confidence: 91,
        landslideScore: 14.5,
        flashFloodScore: 10.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.1,
        susceptibilityContribution: 38.0,
        triggerContribution: 62.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Mawkynrew Ridge',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Mawkynrew',
      location: { type: 'Point', coordinates: [92.0531, 25.4611] },
      populationEstimate: 3400,
      networkReliability: 'WEAK', // High remote ridge / deep shadowing from base stations
      nearestShelter: { name: 'Mawkynrew Block Resource Centre', distanceKm: 1.8 },
      susceptibility: {
        score: 72,
        level: 'HIGH',
        ndviCurrent: 0.49,
        ndviChange5yr: -0.11,
        distanceToMiningSiteKm: 2.6,
        miningActivityType: 'Quarrying & Road Excavation',
        landUseChangeFlag: true,
        slopeAngle: 36,
        elevationMeters: 1580,
        soilErodibilityIndex: 'High (Jointed Siltstone)',
        historicalLandslideDensity: 4,
      },
      currentTelemetry: {
        rainfall24h: 58,
        rainfall72h: 92,
        soilMoisture: 64,
        slopeMovementMm: 0.8,
        waterLevelMeters: 1.6,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WARNING',
        score: 58.6,
        confidence: 72,
        landslideScore: 58.6,
        flashFloodScore: 42.0,
        flashFloodWindow: 'Next 2–6 hours',
        floodExtentSqKm: 0.9,
        susceptibilityContribution: 48.0,
        triggerContribution: 52.0,
        contributingFactors: [
          { name: 'Hill-Road Excavation', weight: 35, description: 'Toe erosion from NH bypass cutting' },
          { name: '24h Rainfall Rate', weight: 35, description: '58 mm' },
          { name: 'Soil Saturation', weight: 30, description: '64%' },
        ],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Pynursla Slope',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Pynursla',
      location: { type: 'Point', coordinates: [91.8988, 25.3094] },
      populationEstimate: 5100,
      networkReliability: 'STRONG', // Highway block junction / major optical fiber transit
      nearestShelter: { name: 'Pynursla Higher Secondary Shelter', distanceKm: 0.9 },
      susceptibility: {
        score: 64,
        level: 'HIGH',
        ndviCurrent: 0.58,
        ndviChange5yr: -0.06,
        distanceToMiningSiteKm: 6.5,
        miningActivityType: 'Minor Sand Extraction & Riverbed Gravel',
        landUseChangeFlag: false,
        slopeAngle: 28,
        elevationMeters: 1240,
        soilErodibilityIndex: 'Moderate (Lateritic Loam & Weathered Sandstone)',
        historicalLandslideDensity: 2,
        drainageDensityKmPerSqKm: 3.2,
        soilType: 'Weathered Sandstone & Clay Loam',
        curveNumber: 82,
        lulcClass: 'Valley Scrub & Subtropical Agricultural Terrace',
        historicalFloodCount: 4,
      },
      currentTelemetry: {
        rainfall24h: 74,
        rainfall72h: 125,
        soilMoisture: 76,
        slopeMovementMm: 0.4,
        waterLevelMeters: 3.1,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WARNING',
        score: 66.8,
        confidence: 80,
        landslideScore: 54.2,
        flashFloodScore: 66.8,
        flashFloodWindow: 'Next 2–4 hours',
        floodExtentSqKm: 2.4,
        runoffMm: 48.6,
        drainageDensity: 3.2,
        susceptibilityContribution: 45.0,
        triggerContribution: 55.0,
        contributingFactors: [
          { name: 'SCS-CN Catchment Runoff Spike', weight: 40, description: '48.6 mm runoff depth in Wah Umngot gorge' },
          { name: 'River Water Level Overtopping', weight: 35, description: '+3.1m above baseline stage' },
          { name: 'High Drainage Density', weight: 25, description: '3.2 km/km² active stream tributaries' },
        ],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Nongstoin Junction Corridor',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Mawphlang',
      location: { type: 'Point', coordinates: [91.7589, 25.4522] },
      populationEstimate: 4200,
      networkReliability: 'STRONG', // Inter-district junction corridor with multiple cellular towers
      nearestShelter: { name: 'Mawphlang Sacred Grove Transit Camp', distanceKm: 2.1 },
      susceptibility: {
        score: 65,
        level: 'HIGH',
        ndviCurrent: 0.51,
        ndviChange5yr: -0.14,
        distanceToMiningSiteKm: 3.2,
        miningActivityType: 'Unregulated Earth Cutting',
        landUseChangeFlag: true,
        slopeAngle: 34,
        elevationMeters: 1390,
        soilErodibilityIndex: 'High',
        historicalLandslideDensity: 3,
      },
      currentTelemetry: {
        rainfall24h: 44,
        rainfall72h: 70,
        soilMoisture: 52,
        slopeMovementMm: 0.3,
        waterLevelMeters: 1.4,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WATCH',
        score: 44.8,
        confidence: 64,
        landslideScore: 44.8,
        flashFloodScore: 32.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.6,
        susceptibilityContribution: 56.0,
        triggerContribution: 44.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Laitkynsew Village',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      stateName: 'Meghalaya',
      blockName: 'Sohra',
      location: { type: 'Point', coordinates: [91.6702, 25.2689] },
      populationEstimate: 1800,
      networkReliability: 'WEAK', // Remote southern valley slope near border with limited BTS line of sight
      nearestShelter: { name: 'Laitkynsew Primary School', distanceKm: 0.6 },
      susceptibility: {
        score: 42,
        level: 'MODERATE',
        ndviCurrent: 0.64,
        ndviChange5yr: -0.04,
        distanceToMiningSiteKm: 5.5,
        miningActivityType: 'None',
        landUseChangeFlag: false,
        slopeAngle: 26,
        elevationMeters: 820,
        soilErodibilityIndex: 'Moderate',
        historicalLandslideDensity: 1,
      },
      currentTelemetry: {
        rainfall24h: 22,
        rainfall72h: 38,
        soilMoisture: 36,
        slopeMovementMm: 0.0,
        waterLevelMeters: 0.9,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'SAFE',
        score: 22.8,
        confidence: 86,
        landslideScore: 22.8,
        flashFloodScore: 18.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.2,
        susceptibilityContribution: 48.0,
        triggerContribution: 52.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },

    // --- DIMA HASAO (ASSAM) ---
    {
      name: 'Haflong Ridge',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Haflong',
      location: { type: 'Point', coordinates: [93.0298, 25.1764] },
      populationEstimate: 16800,
      networkReliability: 'STRONG', // District headquarters & administrative command center
      nearestShelter: { name: 'Haflong District Sports Complex Shelter', distanceKm: 0.8 },
      susceptibility: {
        score: 84,
        level: 'VERY_HIGH',
        ndviCurrent: 0.42,
        ndviChange5yr: -0.19, // Jhum shifting deforestation & Railway cutting
        distanceToMiningSiteKm: 2.1,
        miningActivityType: 'Hill-Cutting & Railway Embankment Subsidence',
        landUseChangeFlag: true,
        slopeAngle: 42,
        elevationMeters: 960,
        soilErodibilityIndex: 'Severe (Disung Shale Formation)',
        historicalLandslideDensity: 8,
      },
      currentTelemetry: {
        rainfall24h: 114,
        rainfall72h: 180,
        soilMoisture: 82,
        slopeMovementMm: 3.4,
        waterLevelMeters: 3.2,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'DANGER',
        score: 86.4,
        confidence: 84,
        landslideScore: 86.4,
        flashFloodScore: 78.0,
        flashFloodWindow: 'Next 2–4 hours',
        floodExtentSqKm: 2.8,
        susceptibilityContribution: 45.0,
        triggerContribution: 55.0,
        contributingFactors: [
          { name: 'Disung Shale Structural Fragility', weight: 35, description: 'Historical 2022 railway subsidence corridor' },
          { name: 'Heavy Monsoon Precipitation', weight: 35, description: '114 mm in 24h' },
          { name: 'Critical Soil Moisture Saturation', weight: 20, description: '82% pore water saturation' },
          { name: 'Extensive Jhum Deforestation', weight: 10, description: '19% NDVI decline over 5 years' },
        ],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Umrangso',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Umrangso',
      location: { type: 'Point', coordinates: [92.7567, 25.5189] },
      populationEstimate: 8200,
      networkReliability: 'STRONG', // Major industrial township (NEEPCO / cement plants) with enterprise connectivity
      nearestShelter: { name: 'NEEPCO Community Hall', distanceKm: 1.4 },
      susceptibility: {
        score: 55,
        level: 'MODERATE',
        ndviCurrent: 0.54,
        ndviChange5yr: -0.09,
        distanceToMiningSiteKm: 1.2, // Limestone cement quarries
        miningActivityType: 'Limestone Open-Cast Quarrying',
        landUseChangeFlag: true,
        slopeAngle: 30,
        elevationMeters: 580,
        soilErodibilityIndex: 'Moderate',
        historicalLandslideDensity: 3,
      },
      currentTelemetry: {
        rainfall24h: 42,
        rainfall72h: 68,
        soilMoisture: 50,
        slopeMovementMm: 0.2,
        waterLevelMeters: 1.8,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WATCH',
        score: 41.2,
        confidence: 66,
        landslideScore: 41.2,
        flashFloodScore: 28.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.5,
        susceptibilityContribution: 54.0,
        triggerContribution: 46.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Mahur Settlement',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Mahur',
      location: { type: 'Point', coordinates: [93.1189, 25.2678] },
      populationEstimate: 4600,
      networkReliability: 'WEAK', // Rugged interior hill topography / intermittent rural tower service
      nearestShelter: { name: 'Mahur Railway School', distanceKm: 1.0 },
      susceptibility: {
        score: 46,
        level: 'MODERATE',
        ndviCurrent: 0.60,
        ndviChange5yr: -0.05,
        distanceToMiningSiteKm: 7.0,
        miningActivityType: 'None',
        landUseChangeFlag: false,
        slopeAngle: 25,
        elevationMeters: 620,
        soilErodibilityIndex: 'Moderate',
        historicalLandslideDensity: 2,
      },
      currentTelemetry: {
        rainfall24h: 24,
        rainfall72h: 40,
        soilMoisture: 38,
        slopeMovementMm: 0.0,
        waterLevelMeters: 1.1,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'SAFE',
        score: 24.5,
        confidence: 84,
        landslideScore: 24.5,
        flashFloodScore: 16.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.2,
        susceptibilityContribution: 50.0,
        triggerContribution: 50.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Maibang Heritage Valley',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Maibang',
      location: { type: 'Point', coordinates: [93.1678, 25.3045] },
      populationEstimate: 5900,
      networkReliability: 'STRONG', // Sub-divisional center along railway and valley highway
      nearestShelter: { name: 'Maibang College Disaster Camp', distanceKm: 0.7 },
      susceptibility: {
        score: 32,
        level: 'LOW',
        ndviCurrent: 0.68,
        ndviChange5yr: -0.02,
        distanceToMiningSiteKm: 10.0,
        miningActivityType: 'None',
        landUseChangeFlag: false,
        slopeAngle: 19,
        elevationMeters: 310,
        soilErodibilityIndex: 'Low (Alluvial Valley Floor)',
        historicalLandslideDensity: 1,
      },
      currentTelemetry: {
        rainfall24h: 16,
        rainfall72h: 28,
        soilMoisture: 30,
        slopeMovementMm: 0.0,
        waterLevelMeters: 0.9,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'SAFE',
        score: 16.2,
        confidence: 90,
        landslideScore: 16.2,
        flashFloodScore: 12.0,
        flashFloodWindow: 'None',
        floodExtentSqKm: 0.1,
        susceptibilityContribution: 42.0,
        triggerContribution: 58.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Jatinga River Gorge',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Haflong',
      location: { type: 'Point', coordinates: [92.9812, 25.1234] },
      populationEstimate: 2100,
      networkReliability: 'WEAK', // Narrow mountain canyon / high terrain attenuation
      nearestShelter: { name: 'Jatinga Inspection Bungalow', distanceKm: 1.5 },
      susceptibility: {
        score: 68,
        level: 'HIGH',
        ndviCurrent: 0.50,
        ndviChange5yr: -0.13,
        distanceToMiningSiteKm: 4.0,
        miningActivityType: 'Unconsolidated Road Debris',
        landUseChangeFlag: true,
        slopeAngle: 38,
        elevationMeters: 740,
        soilErodibilityIndex: 'High',
        historicalLandslideDensity: 5,
      },
      currentTelemetry: {
        rainfall24h: 78,
        rainfall72h: 130,
        soilMoisture: 72,
        slopeMovementMm: 1.6,
        waterLevelMeters: 2.8,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WARNING',
        score: 68.4,
        confidence: 78,
        landslideScore: 68.4,
        flashFloodScore: 62.0,
        flashFloodWindow: 'Next 2–4 hours',
        floodExtentSqKm: 1.8,
        susceptibilityContribution: 46.0,
        triggerContribution: 54.0,
        contributingFactors: [
          { name: 'Jatinga Funnel Catchment Rainfall', weight: 40, description: '78 mm in 24h' },
          { name: 'High Debris Susceptibility', weight: 35, description: 'Steep 38° gorge slope' },
          { name: 'Flash Flood Runoff Potential', weight: 25, description: '2.8m river height' },
        ],
        lastEvaluated: new Date(),
      },
    },
    {
      name: 'Harangajao Riverine Zone',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      stateName: 'Assam',
      blockName: 'Harangajao',
      location: { type: 'Point', coordinates: [92.8645, 25.0456] },
      populationEstimate: 3900,
      networkReliability: 'WEAK', // Remote river valley / prone to power & telecom blackouts during monsoons
      nearestShelter: { name: 'Harangajao High School Shelter', distanceKm: 0.5 },
      susceptibility: {
        score: 62,
        level: 'HIGH',
        ndviCurrent: 0.53,
        ndviChange5yr: -0.08,
        distanceToMiningSiteKm: 5.0,
        miningActivityType: 'Riverbank Quarrying',
        landUseChangeFlag: true,
        slopeAngle: 29,
        elevationMeters: 210,
        soilErodibilityIndex: 'High (Silts & Fine Sands)',
        historicalLandslideDensity: 3,
      },
      currentTelemetry: {
        rainfall24h: 52,
        rainfall72h: 86,
        soilMoisture: 60,
        slopeMovementMm: 0.5,
        waterLevelMeters: 2.3,
        lastReadingTime: new Date(),
      },
      combinedRisk: {
        tier: 'WARNING',
        score: 54.8,
        confidence: 70,
        landslideScore: 54.8,
        flashFloodScore: 52.0,
        flashFloodWindow: 'Next 2–6 hours',
        floodExtentSqKm: 1.2,
        susceptibilityContribution: 50.0,
        triggerContribution: 50.0,
        contributingFactors: [],
        lastEvaluated: new Date(),
      },
    },
  ]);

  // 4. Sensors with multi-mode connectivity & realistic health states
  const sohraZone = riskZones.find(z => z.name.includes('Sohra'));
  const haflongZone = riskZones.find(z => z.name.includes('Haflong'));
  const umrangsoZone = riskZones.find(z => z.name.includes('Umrangso'));

  const sensors = await Sensor.insertMany([
    {
      sensorCode: 'SENS-EKH-01',
      name: 'Sohra Slope Inclinometer & Tilt Array',
      type: 'TILTMETER',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Sohra (Cherrapunji)',
      riskZoneId: sohraZone._id,
      location: { type: 'Point', coordinates: [91.7315, 25.2975] },
      status: 'ONLINE',
      connectivityMode: 'LORAWAN',
      lastReadingValue: 1.2,
      unit: 'mm displacement',
      batteryLevelPct: 92,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-EKH-02',
      name: 'Cherrapunji Automatic Rain Gauge',
      type: 'RAIN_GAUGE',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Sohra (Cherrapunji)',
      riskZoneId: sohraZone._id,
      location: { type: 'Point', coordinates: [91.7330, 25.2990] },
      status: 'ONLINE',
      connectivityMode: 'CELLULAR_4G_WIFI',
      lastReadingValue: 62.0,
      unit: 'mm/24h',
      batteryLevelPct: 98,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-EKH-03',
      name: 'Mawlynnong Soil Moisture Probe',
      type: 'SOIL_MOISTURE',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Mawlynnong',
      location: { type: 'Point', coordinates: [91.9060, 25.2020] },
      status: 'ONLINE',
      connectivityMode: 'GSM_SMS',
      lastReadingValue: 32.0,
      unit: '% saturation',
      batteryLevelPct: 88,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-EKH-04',
      name: 'Mawkynrew Escarpment Vibration Monitor',
      type: 'VIBRATION',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Mawkynrew Ridge',
      location: { type: 'Point', coordinates: [92.0535, 25.4615] },
      status: 'FAULTY_ANOMALY',
      connectivityMode: 'LORAWAN',
      lastReadingValue: 18.5,
      unit: 'mm/s PPV',
      batteryLevelPct: 45,
      lastUpdated: new Date(Date.now() - 45 * 60 * 1000),
      anomalyDetails: {
        isAnomaly: true,
        anomalyType: 'STATISTICAL_SPIKE',
        reason: 'Unphysical piezoelectric transducer spike (Z-Score: 4.2). System using spatial fallback SENS-EKH-02.',
        fallbackSensorId: 'SENS-EKH-02',
      },
    },
    {
      sensorCode: 'SENS-EKH-05',
      name: 'Pynursla Water Level Radar',
      type: 'WATER_LEVEL',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Pynursla Slope',
      location: { type: 'Point', coordinates: [91.8990, 25.3090] },
      status: 'ONLINE',
      connectivityMode: 'GPRS',
      lastReadingValue: 1.2,
      unit: 'meters',
      batteryLevelPct: 84,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-DH-01',
      name: 'Haflong Hill Cut Piezo & Tilt Station',
      type: 'TILTMETER',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Haflong Ridge',
      riskZoneId: haflongZone._id,
      location: { type: 'Point', coordinates: [93.0305, 25.1770] },
      status: 'ONLINE',
      connectivityMode: 'CELLULAR_4G_WIFI',
      lastReadingValue: 3.4,
      unit: 'mm displacement',
      batteryLevelPct: 95,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-DH-02',
      name: 'Haflong Railway Telemetric Rain Gauge',
      type: 'RAIN_GAUGE',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Haflong Ridge',
      riskZoneId: haflongZone._id,
      location: { type: 'Point', coordinates: [93.0290, 25.1760] },
      status: 'ONLINE',
      connectivityMode: 'LORAWAN',
      lastReadingValue: 114.0,
      unit: 'mm/24h',
      batteryLevelPct: 91,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-DH-03',
      name: 'Umrangso Dam Catchment Stream Gauge',
      type: 'WATER_LEVEL',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Umrangso',
      riskZoneId: umrangsoZone._id,
      location: { type: 'Point', coordinates: [92.7570, 25.5195] },
      status: 'OFFLINE',
      connectivityMode: 'GSM_SMS',
      lastReadingValue: 1.8,
      unit: 'meters',
      batteryLevelPct: 12,
      lastUpdated: new Date(Date.now() - 4 * 60 * 60 * 1000), // 4 hrs ago
    },
    {
      sensorCode: 'SENS-DH-04',
      name: 'Jatinga Hydro-Meteorological Station',
      type: 'RAIN_GAUGE',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Jatinga River Gorge',
      location: { type: 'Point', coordinates: [92.9815, 25.1240] },
      status: 'ONLINE',
      connectivityMode: 'CELLULAR_4G_WIFI',
      lastReadingValue: 78.0,
      unit: 'mm/24h',
      batteryLevelPct: 89,
      lastUpdated: new Date(),
    },
    {
      sensorCode: 'SENS-DH-05',
      name: 'Harangajao River Acoustic Sensor',
      type: 'WATER_LEVEL',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Harangajao Riverine Zone',
      location: { type: 'Point', coordinates: [92.8650, 25.0460] },
      status: 'FAULTY_ANOMALY',
      connectivityMode: 'GPRS',
      lastReadingValue: 2.3,
      unit: 'meters',
      batteryLevelPct: 76,
      lastUpdated: new Date(Date.now() - 25 * 60 * 1000),
      anomalyDetails: {
        isAnomaly: true,
        anomalyType: 'FLATLINE',
        reason: 'Constant non-responsive water transducer level across 10 intervals. Maintenance crew notified.',
        fallbackSensorId: 'SENS-DH-04',
      },
    },
  ]);

  // 5. Road Segments
  await RoadSegment.insertMany([
    {
      segmentCode: 'ROAD-EKH-01',
      name: 'NH-206 Sohra-Shella Link Road',
      districtId: 'EKH',
      status: 'CAUTION',
      blockageProbabilityPct: 48,
      criticality: 'LIFELINE_ROAD',
      alternateRouteDescription: 'Via Mawkdok Bypass (Adds 14 km)',
      coordinates: [
        [91.7324, 25.2986],
        [91.7450, 25.2750],
        [91.7600, 25.2400],
        [91.7800, 25.2100],
      ],
      lastInspectionTime: new Date(),
    },
    {
      segmentCode: 'ROAD-EKH-02',
      name: 'SH-5 Shillong-Dawki Border Highway',
      districtId: 'EKH',
      status: 'CLEAR',
      blockageProbabilityPct: 12,
      criticality: 'LIFELINE_ROAD',
      alternateRouteDescription: 'Direct route operational without delay.',
      coordinates: [
        [91.8933, 25.5788],
        [91.9056, 25.3500],
        [91.9056, 25.2017],
      ],
      lastInspectionTime: new Date(),
    },
    {
      segmentCode: 'ROAD-DH-01',
      name: 'Haflong-Lumding Hill Railway & Highway Section',
      districtId: 'DH',
      status: 'BLOCKED',
      blockageProbabilityPct: 88,
      criticality: 'LIFELINE_ROAD',
      alternateRouteDescription: 'Via Mahur-Maibang Alternate Corridor (Adds 32 km)',
      coordinates: [
        [93.0298, 25.1764],
        [93.0800, 25.2200],
        [93.1189, 25.2678],
      ],
      lastInspectionTime: new Date(),
    },
    {
      segmentCode: 'ROAD-DH-02',
      name: 'Umrangso-Lanka Industrial Arterial',
      districtId: 'DH',
      status: 'CLEAR',
      blockageProbabilityPct: 8,
      criticality: 'SECONDARY_ARTERIAL',
      alternateRouteDescription: 'Route fully clear for heavy relief transport.',
      coordinates: [
        [92.7567, 25.5189],
        [92.8500, 25.6000],
        [92.9500, 25.7000],
      ],
      lastInspectionTime: new Date(),
    },
  ]);

  // 6. Active Alerts (Multi-Hazard: Landslides & Flash Floods across EKH & DH)
  const alertHaflong = await Alert.create({
    alertCode: 'ALT-DNG-8401',
    districtId: 'DH',
    districtName: 'Dima Hasao',
    villageName: 'Haflong Ridge',
    riskZoneId: haflongZone._id,
    hazardType: 'LANDSLIDE',
    tier: 'DANGER',
    confidencePct: 84,
    riskScore: 86.4,
    timeWindow: 'Next 2–4 hours',
    contributingSources: [
      'Disung Shale shear zone movement (3.4 mm displacement)',
      '24h Torrential Rainfall (114 mm)',
      'Soil moisture 82%',
      'Historical 2022 railway subsidence alignment',
    ],
    status: 'PENDING_OFFICER_REVIEW', // CRITICAL: Awaiting Officer confirmation
  });

  const alertSohraWarning = await Alert.create({
    alertCode: 'ALT-WRN-6202',
    districtId: 'EKH',
    districtName: 'East Khasi Hills',
    villageName: 'Sohra (Cherrapunji)',
    riskZoneId: sohraZone._id,
    hazardType: 'LANDSLIDE',
    tier: 'WARNING',
    confidencePct: 76,
    riskScore: 64.2,
    timeWindow: 'Next 2–6 hours',
    contributingSources: [
      'Rat-hole coal quarry structural weakness',
      'Rainfall (62 mm in 24h)',
      'Soil saturation 68%',
    ],
    status: 'CONFIRMED_DISPATCHED',
    dispatchChannels: {
      inAppPush: true,
      smsBroadcast: true,
      cellBroadcastSachet: false,
      dispatchedAt: new Date(Date.now() - 35 * 60 * 1000),
    },
    citizenFeedback: {
      totalResponses: 14,
      confirmedAccurateCount: 12,
      falseAlarmCount: 2,
    },
  });

  const alertJatinga = await Alert.create({
    alertCode: 'ALT-WRN-5103',
    districtId: 'DH',
    districtName: 'Dima Hasao',
    villageName: 'Jatinga River Gorge',
    riskZoneId: riskZones.find(z => z.name.includes('Jatinga'))._id,
    hazardType: 'FLASH_FLOOD',
    tier: 'WARNING',
    confidencePct: 78,
    riskScore: 68.4,
    timeWindow: 'Next 2–4 hours',
    floodExtentSqKm: 2.1,
    runoffMm: 44.5,
    drainageDensity: 3.4,
    soilType: 'Disung Silt & Jointed Clay',
    affectedInfrastructure: ['Lumding-Badarpur Hill Railway Line', 'Jatinga River Access Route'],
    overlappingVillages: ['Jatinga River Gorge', 'Haflong Outskirts'],
    contributingSources: [
      'Jatinga Funnel Hourly Rain Spike (78 mm in 24h)',
      'River stage +2.8m above normal baseline',
      'High Drainage Density (3.4 km/km² OSM waterways)',
      'SCS-CN Catchment Inundation: 2.1 km² estimated impact',
    ],
    status: 'CONFIRMED_DISPATCHED',
    dispatchChannels: { inAppPush: true, smsBroadcast: true, dispatchedAt: new Date(Date.now() - 50 * 60 * 1000) },
  });

  const alertPynurslaFlood = await Alert.create({
    alertCode: 'ALT-WRN-7105',
    districtId: 'EKH',
    districtName: 'East Khasi Hills',
    villageName: 'Pynursla Slope',
    riskZoneId: riskZones.find(z => z.name.includes('Pynursla'))._id,
    hazardType: 'FLASH_FLOOD',
    tier: 'WARNING',
    confidencePct: 80,
    riskScore: 66.8,
    timeWindow: 'Next 2–4 hours',
    floodExtentSqKm: 2.4,
    runoffMm: 48.6,
    drainageDensity: 3.2,
    soilType: 'Weathered Sandstone & Clay Loam',
    affectedInfrastructure: ['NH-206 Sohra-Shella Link Road', 'Pynursla Valley Route'],
    overlappingVillages: ['Pynursla Slope', 'Mawlynnong Basin'],
    contributingSources: [
      'SCS-CN Catchment Runoff Spike (48.6 mm depth)',
      'River stage +3.1m above baseline in Wah Umngot gorge',
      'High Drainage Density (3.2 km/km² OSM waterways)',
      'ESA WorldCover: Valley Scrub & Clay Loam soil retention',
    ],
    status: 'CONFIRMED_DISPATCHED',
    dispatchChannels: { inAppPush: true, smsBroadcast: true, dispatchedAt: new Date(Date.now() - 40 * 60 * 1000) },
  });

  const alertHarangajaoFlood = await Alert.create({
    alertCode: 'ALT-WRN-4206',
    districtId: 'DH',
    districtName: 'Dima Hasao',
    villageName: 'Harangajao Riverine Zone',
    riskZoneId: riskZones.find(z => z.name.includes('Harangajao'))._id,
    hazardType: 'FLASH_FLOOD',
    tier: 'WARNING',
    confidencePct: 74,
    riskScore: 58.4,
    timeWindow: 'Next 2–6 hours',
    floodExtentSqKm: 1.9,
    runoffMm: 38.2,
    drainageDensity: 3.1,
    soilType: 'Silts & Fine Sands',
    affectedInfrastructure: ['NH-54 Harangajao Highway Corridor'],
    overlappingVillages: ['Harangajao Riverine Zone'],
    contributingSources: [
      'Riverbank Overtopping Risk (2.3m stage)',
      'SCS-CN Runoff Depth (38.2 mm)',
      'High Drainage Density (3.1 km/km²)',
    ],
    status: 'CONFIRMED_DISPATCHED',
    dispatchChannels: { inAppPush: true, smsBroadcast: true, dispatchedAt: new Date(Date.now() - 75 * 60 * 1000) },
  });

  const alertMawkynrew = await Alert.create({
    alertCode: 'ALT-WAT-3804',
    districtId: 'EKH',
    districtName: 'East Khasi Hills',
    villageName: 'Mawkynrew Ridge',
    riskZoneId: riskZones.find(z => z.name.includes('Mawkynrew'))._id,
    hazardType: 'LANDSLIDE',
    tier: 'WATCH',
    confidencePct: 72,
    riskScore: 58.6,
    timeWindow: 'Next 6–12 hours',
    contributingSources: ['Road cut toe excavation', 'Rainfall 58 mm'],
    status: 'CONFIRMED_DISPATCHED',
    dispatchChannels: { inAppPush: true, dispatchedAt: new Date(Date.now() - 90 * 60 * 1000) },
  });

  // 7. Field Tasks
  const taskSohra = await FieldTask.create({
    taskCode: 'TASK-EKH-091',
    fieldOfficerId: fieldOfficerUser._id,
    fieldOfficerName: fieldOfficerUser.name,
    districtId: 'EKH',
    districtName: 'East Khasi Hills',
    villageName: 'Sohra (Cherrapunji)',
    riskZoneId: sohraZone._id,
    alertId: alertSohraWarning._id,
    title: 'Inspect Slope Tension Cracks near Nohsngithiang Escarpment',
    reason: 'AI flagged elevated warning score (64.2) with potential rat-hole mining subsidence.',
    priority: 'HIGH',
    deadline: new Date(Date.now() + 3 * 60 * 60 * 1000),
    status: 'PENDING',
    location: { type: 'Point', coordinates: [91.7324, 25.2986] },
    checklist: [
      { label: 'Inspect retaining wall behind Village Secondary School', checked: false },
      { label: 'Check for muddy discharge from natural slope springs', checked: false },
      { label: 'Assess NH-206 road shoulder displacement', checked: false },
    ],
  });

  // 8. Citizen Reports
  await CitizenReport.insertMany([
    {
      reportCode: 'REP-EKH-401',
      reporterId: citizenUser._id,
      reporterName: citizenUser.name,
      reporterPhone: citizenUser.phone,
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Sohra (Cherrapunji)',
      category: 'CRACK_LANDSLIDE_SIGN',
      description: 'Noticed 3-inch longitudinal ground crack extending 15 meters along the upper terraced slope behind the primary school.',
      photoUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
      location: { type: 'Point', coordinates: [91.7340, 25.2995] },
      aiPreScreening: {
        confidencePct: 82,
        label: 'High-confidence shear tension fracture',
        isVerifiedLikely: true,
      },
      verificationStatus: 'PENDING',
      submittedAt: new Date(Date.now() - 20 * 60 * 1000),
    },
    {
      reportCode: 'REP-DH-302',
      reporterName: 'Kamal Dimasa',
      reporterPhone: '9876500112',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Haflong Ridge',
      category: 'BLOCKED_ROAD',
      description: 'Minor boulder fall obstructing northbound single lane near Lower Haflong bridge.',
      photoUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
      location: { type: 'Point', coordinates: [93.0310, 25.1780] },
      aiPreScreening: {
        confidencePct: 89,
        label: 'Rockfall debris verified',
        isVerifiedLikely: true,
      },
      verificationStatus: 'VERIFIED',
      verifiedByOfficerId: officerDH._id,
      officerNotes: 'Verified via CCTV and local PWD road patrol.',
      submittedAt: new Date(Date.now() - 65 * 60 * 1000),
    },
  ]);

  // 9. Alert Accuracy Logs (Pre-seeded for 84% accuracy widget)
  const accuracySeedLogs = [];
  for (let i = 1; i <= 45; i++) {
    const isAccurate = i <= 38; // 38 out of 45 = 84.4%
    const hazardType = i <= 28 ? 'LANDSLIDE' : i <= 39 ? 'FLASH_FLOOD' : 'FLOOD_EXTENT';
    accuracySeedLogs.push({
      alertId: i % 2 === 0 ? alertSohraWarning._id : alertJatinga._id,
      alertCode: `HIST-ALT-${1000 + i}`,
      districtId: i % 2 === 0 ? 'EKH' : 'DH',
      villageName: i % 2 === 0 ? 'Sohra' : 'Haflong',
      hazardType,
      predictedTier: i % 3 === 0 ? 'DANGER' : i % 2 === 0 ? 'WARNING' : 'WATCH',
      actualOutcome: isAccurate ? 'ACCURATE_HAZARD_OCCURRED' : 'FALSE_ALARM',
      isAccurate,
      groundEvidenceNotes: isAccurate
        ? (hazardType === 'LANDSLIDE' ? 'Ground slope movement/subsidence verified by field team' : 'Rapid stream surge & overland inundation verified at gorge gauge')
        : 'Precipitation subsided without triggering mass movement',
      contributingCitizenVotes: {
        accurate: isAccurate ? 18 : 2,
        inaccurate: isAccurate ? 2 : 16,
      },
      loggedAt: new Date(Date.now() - (45 - i) * 16 * 60 * 60 * 1000),
    });
  }
  await AlertAccuracyLog.insertMany(accuracySeedLogs);

  // 10. Audit Logs
  await AuditLog.insertMany([
    {
      userId: officerUser._id,
      userName: officerUser.name,
      userRole: 'OFFICER',
      districtId: 'EKH',
      action: 'USER_LOGIN',
      details: 'Officer logged into East Khasi Hills EOC Command Portal.',
      timestamp: new Date(Date.now() - 120 * 60 * 1000),
    },
    {
      userName: 'AI Multi-Hazard Model',
      userRole: 'AI_PREDICTION_SERVICE',
      districtId: 'DH',
      action: 'ALERT_GENERATED',
      details: `AI raised DANGER alert ALT-DNG-8401 for Haflong Ridge (84% conf). Placed in Officer Verification Queue.`,
      metadata: { alertId: alertHaflong._id },
      timestamp: new Date(Date.now() - 80 * 60 * 1000),
    },
    {
      userId: officerUser._id,
      userName: officerUser.name,
      userRole: 'OFFICER',
      districtId: 'EKH',
      action: 'ALERT_CONFIRMED_DISPATCHED',
      details: `Alert ALT-WRN-6202 confirmed and dispatched across SMS & App channels for Sohra.`,
      metadata: { alertId: alertSohraWarning._id },
      timestamp: new Date(Date.now() - 35 * 60 * 1000),
    },
  ]);

  // 11. Durable Notifications
  await Notification.insertMany([
    {
      userId: officerUser._id,
      role: 'OFFICER',
      type: 'ALERT_DANGER',
      relatedEntityId: alertHaflong._id.toString(),
      title: '🚨 Imminent Hazard Alert: Haflong Ridge',
      message: 'AI Multi-Hazard Model escalated Haflong Ridge to DANGER tier (84% confidence). Awaiting verification.',
      villageName: 'Haflong Ridge',
      read: false,
      createdAt: new Date(Date.now() - 40 * 60 * 1000),
    },
    {
      userId: fieldOfficerUser._id,
      role: 'FIELD_OFFICER',
      type: 'FIELD_TASK_ASSIGNED',
      relatedEntityId: taskSohra._id.toString(),
      title: '📋 Priority Ground Task: Sohra School Crack',
      message: 'You have been assigned to inspect active tension cracks behind Sohra primary school.',
      villageName: 'Sohra (Cherrapunji)',
      read: false,
      createdAt: new Date(Date.now() - 25 * 60 * 1000),
    },
    {
      role: 'OFFICER',
      type: 'SOS_BEACON',
      title: '🆘 Distress Beacon: Mawkynrew Ridge',
      message: 'Citizen Dapbianglang Khongwir activated emergency SOS due to slope subsidence.',
      villageName: 'Mawkynrew Ridge',
      read: false,
      createdAt: new Date(Date.now() - 15 * 60 * 1000),
    },
  ]);

  // 12. GSI Historical Landslide Inventory (Task 4)
  await HistoricalLandslide.insertMany([
    // --- East Khasi Hills Past Landslides ---
    {
      eventId: 'GSI-EKH-2022-01',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Sohra (Cherrapunji)',
      date: new Date('2022-06-17'),
      location: { type: 'Point', coordinates: [91.731, 25.295] },
      severity: 'SEVERE',
      description: 'Major debris flow along Mawkdok-Cherra gorge blocking NH-206 during 320mm monsoon deluge.',
      triggerRainfallMm: 320,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-EKH-2022-02',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Mawlynnong',
      date: new Date('2022-07-04'),
      location: { type: 'Point', coordinates: [91.902, 25.204] },
      severity: 'MODERATE',
      description: 'Shallow translational slide on weathered sandstone slope following 140mm intense precipitation.',
      triggerRainfallMm: 140,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-EKH-2023-01',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Mawkynrew Ridge',
      date: new Date('2023-05-28'),
      location: { type: 'Point', coordinates: [91.954, 25.441] },
      severity: 'HIGH',
      description: 'Rotational slope failure across jhum-cultivated terraced slope with deep tension crack propagation.',
      triggerRainfallMm: 185,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-EKH-2023-02',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Pynursla Pass',
      date: new Date('2023-08-12'),
      location: { type: 'Point', coordinates: [91.892, 25.308] },
      severity: 'HIGH',
      description: 'Mudslide on Dauki fault line boundary with rockfall onto state highway corridor.',
      triggerRainfallMm: 195,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-EKH-2024-01',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Mawphlang Fringe',
      date: new Date('2024-06-22'),
      location: { type: 'Point', coordinates: [91.758, 25.452] },
      severity: 'MODERATE',
      description: 'Soil slip on degraded slope along riverbank cutting pedestrian access path.',
      triggerRainfallMm: 130,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-EKH-2024-02',
      districtId: 'EKH',
      districtName: 'East Khasi Hills',
      villageName: 'Sohra Rim (Laitryngew)',
      date: new Date('2024-07-15'),
      location: { type: 'Point', coordinates: [91.741, 25.305] },
      severity: 'HIGH',
      description: 'Sub-surface subsidence collapse linked to historical rat-hole coal shafts beneath hillside.',
      triggerRainfallMm: 210,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },

    // --- Dima Hasao Past Landslides ---
    {
      eventId: 'GSI-DH-2022-01',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Haflong Hill Railway Section',
      date: new Date('2022-05-15'),
      location: { type: 'Point', coordinates: [93.021, 25.172] },
      severity: 'SEVERE',
      description: 'Major structural landslide inundating New Haflong railway station tracks and embankment.',
      triggerRainfallMm: 340,
      casualties: 2,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-DH-2022-02',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Jatinga Valley Escarpment',
      date: new Date('2022-05-19'),
      location: { type: 'Point', coordinates: [93.045, 25.121] },
      severity: 'HIGH',
      description: 'Massive Disung shale debris slide severing NH-54 highway connectivity for 5 days.',
      triggerRainfallMm: 275,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-DH-2023-01',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Umrangso Reservoir Catchment',
      date: new Date('2023-06-11'),
      location: { type: 'Point', coordinates: [92.778, 25.512] },
      severity: 'MODERATE',
      description: 'Limestone karst slope slumping adjacent to Kopili hydro-electric reservoir rim.',
      triggerRainfallMm: 160,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-DH-2023-02',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Mahur Ghat Section',
      date: new Date('2023-07-29'),
      location: { type: 'Point', coordinates: [93.118, 25.185] },
      severity: 'HIGH',
      description: 'Deep-seated rotational failure in weathered Disung sandstone-shale interbeds.',
      triggerRainfallMm: 220,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-DH-2024-01',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Harangajao Valley',
      date: new Date('2024-06-03'),
      location: { type: 'Point', coordinates: [92.865, 25.021] },
      severity: 'SEVERE',
      description: 'Flash-flood assisted embankment slide causing complete road breach on arterial link.',
      triggerRainfallMm: 290,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
    {
      eventId: 'GSI-DH-2024-02',
      districtId: 'DH',
      districtName: 'Dima Hasao',
      villageName: 'Maibang Highway Spur',
      date: new Date('2024-08-08'),
      location: { type: 'Point', coordinates: [93.162, 25.295] },
      severity: 'MODERATE',
      description: 'Road-cut slope instability and rock-fall along Lumding-Silchar hill corridor.',
      triggerRainfallMm: 155,
      casualties: 0,
      source: 'Geological Survey of India (GSI) Landslide Inventory',
    },
  ]);

  console.log('✅ Database seeded with 12 NER villages, realistic sensors, active alerts, road segments, notifications, historical landslides, and accuracy logs!');
};
